# Generated by Django 5.2.1 on 2025-06-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_rename_facebooks_customuser_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
